name: PHP Composer

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.4", "8.5" ]
        dependencies: [ "lowest", "highest" ]

    name: PHP ${{ matrix.php-version }} (${{ matrix.dependencies }} deps)

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, intl, gd, imagick, bcmath, soap, zip, pcov
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run test suite
        run: composer run-script test
